package test.UserGroupService;

import BaseURL.UserGroupServiceBaseURL;

import io.restassured.response.Response;
import org.testng.annotations.Test;
import testData.UserGroupServiceData;

import static io.restassured.RestAssured.given;
import static org.junit.Assert.assertEquals;

public class GET_GetAllUserGroup extends UserGroupServiceBaseURL {


    @Test
    public  void GetAllUserGroup(){

        specification.pathParams("usergroupPath","user-group");

        UserGroupServiceData data = new UserGroupServiceData();
        System.out.println("Expected Test Data:"+data.statusCodeForGet());

        Response response = given().
                spec(specification).
                when().
                header("Authorization","Bearer eyJraWQiOiIyOGQ1MDVjMy01MDgxLTQwOGEtOGU0NC01NTgzMTYxN2EwYjQiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJib0B0ZXN0aW9uZXh1cy5jb20iLCJzdWJfZGVmYXVsdF9tZW1iZXJzaGlwX3R5cGVfaWQiOjUsInN1Yl9pZCI6MjI3LCJzdWJfZGVmYXVsdF9zdWJzY3JpcHRpb25faWQiOiI0YWYzYmMyNS1jZDI0LTRkMjItYTk2Ny1mZWM0ZDI4NzI0YTYiLCJzdWJfYXBwIjoyLCJpc3MiOiJodHRwczpcL1wvYTNtLXFhLWdtMy5xdWFzcGFyZXBhcnRzLmNvbSIsInN1Yl9kZWZhdWx0X29yZ19pZCI6MjQsImF1ZCI6IjE2NzM5ODUxODRfWlhzTlQ3Q3VoVHpyaWpsIiwibmJmIjoxNjgwNjI2MzYzLCJzdWJfZGVmYXVsdF9vcmdfbmFtZSI6Imdyb3VwMDA0Iiwic2NvcGUiOlsiUk9MRV9CdXNpbmVzcyBPd25lciIsImFwcGxpY2F0aW9uOnJlYWQiLCJvcmRlcjp3cml0ZSIsImZpbGU6d3JpdGUiLCJpbnZlbnRvcnk6cmVhZCIsInJlY2VwdGlvbjpjb25maXJtIiwid2lzaGxpc3Q6YXBwcm92ZWQiLCJpbnZvaWNlOnJlYWQiLCJpbnZlbnRvcnk6d3JpdGUiLCJST0xFX1B1cmNoYXNlIE1hbmFnZXIiLCJ1c2VyLXJvbGU6cmVhZCIsImRhc2hib2FyZDpyZWFkIiwicGVybWlzc2lvbjp3cml0ZSIsInVzZXI6d3JpdGUiLCJzcGVjcHJpY2U6cmVhZCIsIlJPTEVfUHVyY2hhc2UgUGVyc29ubmVsIiwiYWNjb3VudGluZzp3cml0ZSIsInVzZXItb3JnYW5pemF0aW9uOnJlYWQiLCJ1c2VyLWdyb3VwOnJlYWQiLCJzcGVjcHJpY2U6d3JpdGUiLCJjb21wYW55OmFkbWluIiwibWVtYmVyc2hpcC10eXBlOndyaXRlIiwicm9sZTp3cml0ZSIsInBlcm1pc3Npb246cmVhZCIsInB1cmNoYXNpbmc6Y29uZmlybSIsInJlY2VwdGlvbjpyZWFkIiwid2lzaGxpc3Q6cXVhbGl0eV9jb25maXJtIiwidXNlci1ncm91cDp3cml0ZSIsInVzZXItc3RhdHVzOnJlYWQiLCJjb3VudHJ5OnJlYWQiLCJtZW1iZXJzaGlwLXR5cGU6cmVhZCIsInByb2N1cmVtZW50OnJlYWQiLCJvcmdhbml6YXRpb24tc3RhdHVzOndyaXRlIiwiY29tcGFueTpyZWFkIiwiY29tcGFueTpmaW5fY29uZmlybSIsInVzZXItc3RhdHVzOndyaXRlIiwid2lzaGxpc3Q6c2V0X2NvZGluZyIsInVzZXItZ3JvdXAtdHlwZTpyZWFkIiwidXNlci1yb2xlOndyaXRlIiwid2lzaGxpc3Q6b2ZmZXJfcmVhZHkiLCJwdXJjaGFzaW5nOnJlYWQiLCJvcmdhbml6YXRpb246cmVhZCIsIndpc2hsaXN0OmFkbWluIiwib3JkZXI6cmVhZCIsInVzZXItb3JnYW5pemF0aW9uOndyaXRlIiwiaGFuZG1hZGU6d3JpdGUiLCJ3aXNobGlzdDpvZmZlcl9jb25maXJtIiwid2lzaGxpc3Q6Y2FuY2VsIiwiYXBwbGljYXRpb246d3JpdGUiLCJzdWJzY3JpcHRpb246cmVhZCIsImNvbXBhbnk6d3JpdGUiLCJmaWxlOnJlYWQiLCJ1c2VyOnJlYWQiLCJ1c2VyLWdyb3VwLXR5cGU6d3JpdGUiLCJvcmdhbml6YXRpb24tZ3JvdXA6cmVhZCIsImludm9pY2U6d3JpdGUiLCJoYW5kbWFkZTpjb25maXJtIiwiUk9MRV9TYWxlcyBNYW5hZ2VyIiwicmVjZXB0aW9uOndyaXRlIiwid2lzaGxpc3Q6c2V0X3ByaWNlIiwib3JnYW5pemF0aW9uOndyaXRlIiwicm9sZTpyZWFkIiwibWVtYmVyc2hpcDpyZWFkIiwid2lzaGxpc3Q6c2FsZV9jb25maXJtIiwib3JnYW5pemF0aW9uLWdyb3VwOndyaXRlIiwicHVyY2hhc2luZzp3cml0ZSIsImludm9pY2U6Y29uZmlybSIsImNsaWVudDp3cml0ZSIsImhhbmRtYWRlOnJlYWQiLCJwcm9jdXJlbWVudDp3cml0ZSIsIm9yZ2FuaXphdGlvbi1zdGF0dXM6cmVhZCIsImNvbXBhbnk6cXVhbF9jb25maXJtIiwicHVyY2hhc2luZzpyZWFkX2Nvc3QiLCJtZW1iZXJzaGlwOndyaXRlIiwiYWNjb3VudGluZzpyZWFkIiwib3JkZXI6Y29uZmlybSIsInN1YnNjcmlwdGlvbjp3cml0ZSIsIndpc2hsaXN0OnJlYWQiLCJjbGllbnQ6cmVhZCJdLCJzdWJfZGVmYXVsdF9yb2xlX2lkIjo1LCJleHAiOjE2ODA2MjgxNjMsImlhdCI6MTY4MDYyNjM2M30.ffIwHd9TUau7bj-Vb3xotXGeAjW1hplcrK0qbtPHTeqJyhLcmKGlZGaFjY3LYBSpv7-y66cMwgBfrC9V137ky7z5jXHO1n5BqOS-mZxE-t-D5M5OuNCrXRSz6cnIzY48L-Gl9VsuKI8ZkbB-1rKYwA6ey9Q-HXM4NWufKi3KJazCAyQLSeWVJK5tlmjOp44uKO2n1IKR8cx_xLBJ5dowaktcq_G54a9tYL7dC-l6L9A7kQ2jaaDvL0T-ipZdDJHNMEVnbrmBS-8aZwEMbQr1TxZ-LxWAea7YEekfJUTVQ1ieYyKlUTJlf-jef6EBj8lZ_gh8xmi0i3om-qxKe-WDig").
                get("/{usergroupPath}");

        System.out.println("Response:");
        response.prettyPrint();

        response.then().assertThat().statusCode(200);
       assertEquals(data.statusCodeForGet(), response.statusCode());
    }


}
